### ISSUE TITLE
Preferred Output

### ISSUE THREAD

**Issue by chrisk123999** [skyboy/NetherOres#29]
Requesting a way to select the exact ingot/dust for everything this mod detects.  Right now I'm running into the issue where Nether Diamond Ore is getting turned into Diamond Dust from IC2 instead of turning into the gem.  Also it would be nice to have the machines it registers to output the same dust from that mod machine it is using (Thermal Expansion pulverizer should output pulverized copper instead of copper dust from IC2).

**Comment by Nova001Sol** [comment]
This. It's the same issue I'm having when I install ElectriCraft.

**Comment by skyboy** [comment]
I don't have control enough over the ore dictionary to implement this.
