### ISSUE TITLE
Vanilla Furnace SMP doesn't work

### ISSUE THREAD

**Issue by Tsunayoshi** [skyboy/NetherOres#32]
Hey,

I have a problem with:
NetherOres-[1.7.10]2.3.0RC4-9.jar
CoFHCore-[1.7.10]3.0.0B9-96.jar

my private pack has only tinkers so I have to use the vanilla furnace to smelt down the nether ores, but every time when I put my nether ores in the vanilla furnace, the furnace starts running. But if I leave the gui, the nether ores get back in my inventory. The furnace is still running until I open the gui again (sync issue).

I seems that the client know what to do, but the server doesn't allow it. Configs are the same for client and server side.

**Comment by Tsunayoshi** [comment]
It seems other mods like witchery have the same problem. So I can't say by 100% it comes from nether ores...

**Comment by skyboy** [comment]
Your version and the server's version are not the same.

**Comment by Tsunayoshi** [comment]
Versions was the same... An update of CoFHCore solved this problem.
