### ISSUE TITLE
Crash when breaking Vanilla Nether Quartz Ores

### ISSUE THREAD

**Issue by ultrasn0w** [skyboy/NetherOres#34]
Hey there,
Whenever I try to break a vanilla Nether Ore my Minecraft crashes and the log spits out this:
http://pastebin.com/DEmaX1vz

Greetings ultrasn0w

**Comment by skyboy** [comment]
This appears to be a bug with the customitems mod

**Comment by ultrasn0w** [comment]
Confirmed, closing.
