### ISSUE TITLE
Using netherores in rfTools dimensions with explosions enabled causes a crash, superfulous chunks to be spawned

### ISSUE THREAD

**Issue by utoc** [skyboy/NetherOres#38]
Good day,

Recently a user was creating a new rfTools dimension (similar to Mystcraft) using "Nether Gold" as their material block of choice.  Upon loading into the dimension, the server crashed.  Pastebin here: http://pastebin.com/bjBFWHpR Further more, upon examanation of the world/DIM8/region directory, there were places listed that were x/z > 6000 before even having a chance to leave the spawn point in the world.

Setting B:ExplosionEnable=false caused the world to load properly and kept the server from creating excessive amounts of chunks

**Comment by skyboy** [comment]
This should largely be resolved, as ores should not explode when chunks are generating any longer (2.3.1 RC1+).
