### ISSUE TITLE
[Enhancement] AE2 Certus Quartz Ore

### ISSUE THREAD

**Issue by mcgraj3** [skyboy/NetherOres#39]
I would really like to see Applied Energistics 2's Certus Quartz Ore incorporated into NetherOres. It is a crucial part of AE2's entire system (the mod is built upon this single ore) and after doing heavy mining in the Nether, I'd like to see it get added. Thanks!

**Comment by skyboy** [comment]
The AE2 devs do not want it added to NetherOres, for lore-consistency with their mod.
