### ISSUE TITLE
Incompatibility with GregTech 5/6

### ISSUE THREAD

**Issue by SirAzazel** [skyboy/NetherOres#40]
This Error was first got on my main modpack, I'll attach modlist if needed. Error was reproduced on modpack with just nether ores, gregtech and all needed addons (ic2 and COFH Core).
Crash is happening during the PostInitialization phase, right at the end, when it proceeds to Avaliable state. [Crash Report](http://pastebin.com/M5h228QU).
*Sorry for my bad English. Thanks.*

**Comment by SirAzazel** [comment]
Looks like duplicate of [this](https://github.com/CoFH/Feedback/issues/292). Sorry.

**Comment by SirAzazel** [comment]
Guys in greg's thread sayed that it's nether ores issue in [this](http://forum.industrial-craft.net/index.php?page=Thread&postID=192773#post192773) post. Well, nether ores and gregtech will be bad to have both at the same time, but still, it's error. I'll reopen this issue just in case.

**Comment by Blood-Asp** [comment]
Quite easy to fix on this side.
https://github.com/skyboy/NetherOres/blob/master/src/powercrystals/netherores/ores/Ores.java#L263
change: "if (NetherOresCore.enableMaceratorRecipes.getBoolean(true) &&Loader.isModLoaded("IC2"))" into "if (NetherOresCore.enableMaceratorRecipes.getBoolean(true) &&Loader.isModLoaded("IC2"))&&(!Loader.isModLoaded("gregtech"))"

**Comment by skyboy** [comment]
This error was introduced into the IC2 source by greg, he can fix it.
