### ISSUE TITLE
Compatibility issue: Nether Ores breaks Gendustry localization for user-defined bee species and items.

### ISSUE THREAD

**Issue by SargeRyong** [skyboy/NetherOres#41]
When and only-when Nether Ores is present in the environment, Gendustry is unable to load user-defined localization files.   Uninstalling NetherOres causes the issue to vanish.

Please see Gendustry issue https://github.com/bdew/gendustry/issues/132

**Comment by skyboy** [comment]
Commented on the linked issue.

**Comment by SargeRyong** [comment]
Thanks for lending your attention to the issue!
