### ISSUE TITLE
Mod rejection on connection

### ISSUE THREAD

**Issue by LemADEC** [skyboy/NetherOres#42]
When connecting to a server without NetherOres installed, client can't connect with "Mod rejections" message. This prevents us to have a common hub for our modpacks, since not all of them will have this mod in it, or might use different version.
Apparently, RedstoneArsenal has the same issue, so I'm not sure if it the rootcase is in CoFHcore itself?

**Comment by skyboy** [comment]
This is not a bug. This is the correct behavior for content-adding mods.

**Comment by LemADEC** [comment]
I've 70 mods in the pack, those 2 are the only one having this incorrect behavior.
All other mods will accept connecting while being only installed on client.

**Comment by skyboy** [comment]
The behavior is not incorrect. This was the default behavior in 1.6, and in 1.7 forge introduced the bug where content-adding mods default to allowing such connections, which causes all kinds of subtle problems, and occasional complete crashes.

There is, and will be, no discussion. Our mods are required on *both* sides. Always.
