### ISSUE TITLE
config for what to get

### ISSUE THREAD

**Issue by Goten87** [skyboy/NetherOres#43]
i have some issuse with the lapis prosessing
can you not make it in the config what we will get
now its looking for dust first for all i think
so if i pulverize lapis i get the dust and i can only use that on IC2 so will it not be nicer to say like  pulverize lapis will become lapis normal in the config
same as nether iron ore it will become the ic2 dust in a pulverizer thats not what i want i want to have the pulverize iron from it

**Comment by skyboy** [comment]
You can smelt the ores into the vanilla ores first to get the regular drops from them, though there is no reliable way for me to select a certain mod's dust, so you just get whatever comes out.
